=== exasol/dynamodb-virtual-schema/src/main/resources/mappingLanguageSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/exasol/dynamodb-virtual-schema/blob/develop/src/main/resources/mappingLanguageSchema.json",
  "definitions": {
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "The Description Schema",
      "description": "An explanation about the purpose of this instance."
    },
    "maxLength": {
      "type": "integer",
      "default": 254
    },
    "children": {
      "$id": "#/properties/children",
      "type": "object",
      "title": "",
      "description": "An explanation about the purpose of this instance.",
      "minProperties": 1,
      "additionalProperties": {
        "type": "object",
        "anyOf": [
          {
            "title": "object with no mapping",
            "properties": {
              "description":{
                "$ref": "#/definitions/description"
              },
              "children": {
                "$ref": "#/definitions/children"
              }
            },
            "additionalProperties":false
          },
          {
            "title": "toString mapping definition",
            "properties": {
              "mapping": {
                "const": "toString"
              },
              "maxLength": {"$ref": "#/definitions/maxLength"},
              "overflow": {
                "default": "TRUNCATE",
                "enum": ["TRUNCATE", "ABORT"]
              },
              "destName": {
                "type": "string"
              },
              "description":{
                "$ref": "#/definitions/description"
              }
            },
            "required": ["mapping"],
            "additionalProperties":false
          },
          {
            "title": "toJSON mapping definition",
            "properties": {
              "mapping": {
                "const": "toJSON"
              },
              "maxLength": {"$ref": "#/definitions/maxLength"},
              "overflow": {
                "default": "NULL",
                "enum": ["NULL", "ABORT"]
              },
              "description":{
                "$ref": "#/definitions/description"
              }
            },
            "required": ["mapping"],
            "additionalProperties":false
          },
          {
            "title": "toTable mapping definition",
            "properties": {
              "mapping": {
                "const": "toTable"
              },
              "destTableName": {
                "type": "string"
              },
              "children": {
                "$ref": "#/definitions/children"
              },
              "description":{
                "$ref": "#/definitions/description"
              }
            },
            "required": ["mapping"],
            "additionalProperties":false
          }
        ]
      }
    }
  },
  "type": "object",
  "title": "The Root Schema - Represents the mapping rom a DynamoDB table to an Exasol Virtual Schema table",
  "description": "The root schema comprises the entire JSON document.",
  "additionalProperties": false,
  "required": [
    "$schema",
    "srcTable",
    "destTableName",
    "children"
  ],
  "properties": {
    "$schema": {
      "$id": "#/properties/$schema",
      "type": "string",
      "enum": [
        "https://github.com/exasol/dynamodb-virtual-schema/blob/develop/src/main/resources/mappingLanguageSchema.json",
        "../../main/resources/mappingLanguageSchema.json"
      ]
    },
    "srcTable": {
      "$id": "#/properties/srcTable",
      "type": "string",
      "title": "DynamoDB table name",
      "description": "the identifier of the DynamoDB table",
      "examples": [
        "MY_BOOKS"
      ]
    },
    "destTableName": {
      "$id": "#/properties/destTableName",
      "type": "string",
      "title": "name of the table in Exasol Virtual Schema",
      "description": "the name of the resulting table in Exasol. The name must only contain [a-z A-Z 0-9]",
      "examples": [
        "BOOKS"
      ]
    },
    "description": {
      "$ref": "#/definitions/description"
    },
    "children": {
      "$ref": "#/definitions/children"
    }
  }
}

=== exasol/dynamodb-virtual-schema/src/test/resources/toJsonMapping.json
{
  "$schema": "../../main/resources/mappingLanguageSchema.json",
  "srcTable": "MY_BOOKS",
  "destTableName": "BOOKS",
  "description": "Maps MY_BOOKS to BOOKS with toJSON",
  "children": {
    "isbn": {
      "mapping": "toString",
      "maxLength": 20,
      "overflow": "ABORT"
    },
    "name": {
      "mapping": "toString",
      "maxLength": 100,
      "overflow": "TRUNCATE"
    },
    "topics":{
      "mapping": "toJSON",
      "description": "Maps the sub document of this property to a JSON string",
      "maxLength": 200
    }
  }
}

=== exasol/dynamodb-virtual-schema/src/test/resources/invalidToTableMappingWithNoChildren.json
{
  "$schema": "../../main/resources/mappingLanguageSchema.json",
  "srcTable": "MY_BOOKS",
  "destTableName": "BOOKS",
  "description": "Maps MY_BOOKS to BOOKS with toJSON",
  "children": {
    "isbn": {
      "mapping": "toString",
      "maxLength": 20,
      "overflow": "ABORT"
    },
    "name": {
      "mapping": "toString",
      "maxLength": 100,
      "overflow": "TRUNCATE"
    },
    "topics":{
      "mapping": "toTable",
      "description": "Maps the strings in this list to rows in the separate table BOOKS_TOPICS",
      "children": {
      }
    }
  }
}
